# Generated by Django 5.2.1 on 2025-05-19 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('camera_type', models.CharField(choices=[('ip', 'IP Camera'), ('rtsp', 'RTSP Camera'), ('usb', 'USB Camera'), ('onvif', 'ONVIF Camera')], default='rtsp', max_length=20)),
                ('stream_url', models.CharField(max_length=500)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(default=554)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('inactive', 'Inactive'), ('error', 'Error')], default='offline', max_length=20)),
                ('last_online', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detection_enabled', models.BooleanField(default=True)),
                ('fire_smoke_detection', models.BooleanField(default=True)),
                ('fall_detection', models.BooleanField(default=True)),
                ('violence_detection', models.BooleanField(default=True)),
                ('choking_detection', models.BooleanField(default=True)),
                ('face_recognition', models.BooleanField(default=False)),
                ('confidence_threshold', models.FloatField(default=0.6)),
                ('iou_threshold', models.FloatField(default=0.45)),
                ('image_size', models.IntegerField(default=640)),
                ('frame_rate', models.IntegerField(default=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera',
                'verbose_name_plural': 'Cameras',
                'ordering': ['-created_at'],
            },
        ),
    ]
