# Generated by Django 5.2.1 on 2025-05-19 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cameras', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('face_image', models.ImageField(upload_to='faces/images/')),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('access_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorized_faces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authorized Face',
                'verbose_name_plural': 'Authorized Faces',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FaceVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_match', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_image', models.ImageField(blank=True, null=True, upload_to='faces/verification/')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('authorized_face', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='faces.authorizedface')),
                ('source_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_verifications', to='cameras.camera')),
            ],
            options={
                'verbose_name': 'Face Verification Log',
                'verbose_name_plural': 'Face Verification Logs',
                'ordering': ['-verified_at'],
            },
        ),
    ]
